### ISSUE TITLE
Apex legends blocking the application

### ISSUE THREAD

**Issue by ThiccNippls** [SaifAqqad/AHK_MicMute#112]
When i try to run apex legend with the software running i get the following error message:
![Screenshot 2024-12-20 095007](https://github.com/user-attachments/assets/c2bf86ff-b3ac-4264-9c73-5a0b94b2664d)

There's a similar discontinued [project](https://github.com/iXab3r/MicSwitch/releases/tag/1.0.253) that runs with no issues although not as polished as yours and a bit buggy, could help you fix the issue of games detecting the app as cheat.

**Comment by SaifAqqad** [comment]
This happens because this app is written using AutoHotkey which is often used to write macro scripts and cheats which in turn makes game companies target AutoHotkey itself with their anti-cheat systems.

I can't really do anything about this, if you want to be 100% safe from account bans, etc, you should stick to other [alternatives](https://alternativeto.net/software/ahk-micmute/)
