### ISSUE TITLE
[Feature Request] Ability to change on/off sounds in the config file.

### ISSUE THREAD

**Issue by AlexAndHisScripts** [SaifAqqad/AHK_MicMute#14]
And thanks for making this software - MS teams doesn't have push to talk.

It would also be nice to have documentation on building the application so we can change it ourselves. To other people, on windows go to:
``C:\Program Files\AutoHotkey\Compiler``
Then run:
``.\Ahk2Exe.exe /in [path to the git repo]MicMute.ahk``

A .exe will be generated at the git repo path.

**Comment by SaifAqqad** [comment]
Hey, I'm actually working on this right now because I recently replaced discord's sounds with original sounds that I made, so I'm also adding the ability to use custom sounds just in case they're horrible 😄 

also as to build the application just run 
`Ahk2Exe.exe /in "path\to\MicMute.ahk" /out "path\to\MicMute.exe"`

**Comment by SaifAqqad** [comment]
🎉 [Check the latest release](https://github.com/SaifAqqad/AHK_MicMute/releases/tag/0.7.8.1) 🎉
