### ISSUE TITLE
[Request] Сustom microphone icon 

### ISSUE THREAD

**Issue by toolewdpersona** [SaifAqqad/AHK_MicMute#28]
I wanted to be able to change the microphone icon to my own in the overlay. Similar to how it is done with sounds.
You can also add settings for the position of the icon on the screen.

**Comment by SaifAqqad** [comment]
I'll see what I can do, but there's a potential problem with changing the icon, because the background color of the overlay window is gray (#232323) which is made transparent when the overlay is locked, so if the icon also had that color in it, it will also become transparent (or some parts of it will).

Also you can already change the overlay position, just press <kbd>CTRL</kbd><kbd>Alt</kbd><kbd>F10</kbd> to unlock the overlay and then drag it to the position you want and relock it afterwards.

**Comment by toolewdpersona** [comment]
> Also you can already change the overlay position, just press CTRL Alt F10 to unlock the overlay and then drag it to the position you want and relock it afterwards.

Sorry, I didn't notice.
It's really handy!

**Comment by SaifAqqad** [comment]
Hey, I just released the [new version](https://github.com/SaifAqqad/AHK_MicMute/releases/tag/1.1.1),  you can download it and test out the feature.
I've also added instructions for using it in the [README](https://github.com/SaifAqqad/AHK_MicMute#3-on-screen-overlay)
