### ISSUE TITLE
switching between profiles

### ISSUE THREAD

**Issue by Auncaughbove17** [SaifAqqad/AHK_MicMute#38]
Hey! Great App!
I have one issue with it though. I use two profiles. ([gist with config](https://gist.github.com/Auncaughbove17/c04cdcb383cfc27606d74b1f4d112dea)) One for ms teams which I use exclusively for University and always want to use push to talk with, and one for private use in discord, in which I always wnat to have an open mic (or toggle).  

Now my issue is that the program only switches profile when I **close** the app i.e. end the task and then open the other app. Not when it's minimized. This is an issue for me since I want both always running in the background. Would it be possible to change when the target window becomes active, instead of when it starts?

Alternatively I would be fine with the possibility to set a hotkey to switch profiles. 

Do you think you could implement either of these features? 

Thanks for your work and I hope you can help me :)

**Comment by SaifAqqad** [comment]
> Now my issue is that the program only switches profile when I close the app i.e. end the task and then open the other app. Not when it's minimized. This is an issue for me since I want both always running in the background. Would it be possible to change when the target window becomes active, instead of when it starts?

The linked app feature actually checks if a window exists for that app, not if the app is running or not.
So when the discord or teams window is closed (even if the app is running in the background) it should switch back to the default profile, however, in the case of teams, that's not working because the teams window is never actually hidden, instead the window is just minimized and the taskbar icon is hidden.
to fix this I'll just add an extra check so if the window is minimized, it will switch back to the default profile.

**Comment by SaifAqqad** [comment]
Commit 1cf7f8d should fix it, You can test it out in the [development build](https://github.com/SaifAqqad/AHK_MicMute/releases/tag/latest_commit).
