### ISSUE TITLE
Notification of administrator privileges

### ISSUE THREAD

**Issue by gitmaker032** [SaifAqqad/AHK_MicMute#50]
Sometimes I get this notification when the app is running. At the same time there are no problems with hotkeys and other functionality, everything works fine. I don't quite understand why this notification appears.

![librewolf_NIQi7G1vDJ](https://user-images.githubusercontent.com/67278783/146391297-ece776ba-e646-4643-8d36-d6c1501b4581.png)

**Comment by SaifAqqad** [comment]
This notification appears whenever you use an app that's elevated (running as administrator) while MicMute isn't, because hotkeys will not work while the elevated app is in focus.

It's just a warning that you can safely ignore, but if it's too annoying you can right click on the notification and turn it off
