### ISSUE TITLE
issue with Control+` hotkey

### ISSUE THREAD

**Issue by Gambyjuk** [SaifAqqad/AHK_MicMute#91]
On program startup, if windows keyboard layout is switched to RU "invalid keys in profile" error shows up, When it switched to EN, program lunches with no issues and this hotkey recognized with no problem, even when layout switched from EN to RU.

As a work around I switched main layout to EN for now so this error stop annoying me on windows startup. But if its a bug and not windows shenanigan's that would be great if this can be fixed.

` ( or ~) key is from what i noticed  the only key that have this issue, when i change hotkey to something else issue disappears.
![Снимок экрана (24)](https://github.com/SaifAqqad/AHK_MicMute/assets/96685454/88515895-1fe4-48a1-ba66-5533c459935b)

![NVIDIA_Share_XoEALKCnzC](https://github.com/SaifAqqad/AHK_MicMute/assets/96685454/821bd9f0-bbe5-4650-b834-9a4961ad5a42)

**Comment by SaifAqqad** [comment]
I pushed a fix for this, but you'll need to re-record the hotkey in the UI for it to take effect, as it will now use the virtual key code instead of the key names when storing the hotkey.

You can test it in the [latest dev build](https://github.com/SaifAqqad/AHK_MicMute/releases/tag/latest_commit).

**Comment by Gambyjuk** [comment]
Works like a charm, thank you.
